default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host:     <%= ENV['DB_HOSTNAME'] %>
  port:     <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

staging:
  <<: *default
  database: travelit_staging

development:
  <<: *default
  reconnect: false
  database: travelit_development

test:
  <<: *default
  database: travelit_test

demo:
  <<: *default
  database: travelit_demo

production:
  <<: *default
  database: travelit_production
